### ISSUE TITLE
Issue linking to #id within page #124

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-docsviewer#104]
e.g. https://docs.silverstripe.org/en/3.3/changelogs/3.2.0/

If you look at the link to "Major Changes" (which points to #major-changes) it links to the current URL without the last URL segment.

**Comment by patricknelson** [comment]
Not sure where this bug is coming from. Due to unfamiliarity with how this works, I had to give up since I ran out of time. I wasn't able to take the time to track down exactly how it determines the value set for `$entity->setVersion($version);` (in the `DocumentationManifest`). I'm just assuming that's how the markdown parser is at least determining how to prefix `#` (via `->getLink()` on the `DocumentationEntity`). No clue :neutral_face:

**Comment by camfindlay** [comment]
Thanks @patricknelson seems there is a few outstanding items on docsviewer. Will have to get some time in to look at this.

**Comment by UndefinedOffset** [comment]
@camfindlay I think it's something to do with this [line 448 in DocumentationParser](https://github.com/silverstripe/silverstripe-docsviewer/blob/master/code/DocumentationParser.php#L448). It could be as simple as removing the dirname call. But I'd need to do some more poking to be sure removing it doesn't break something else.

**Comment by UndefinedOffset** [comment]
Doesn't look like it's that easy ;) doing what I suggested causes the unit tests to start to fail for example [this assertion](https://github.com/silverstripe/silverstripe-docsviewer/blob/master/tests/DocumentationParserTest.php#L187-L190). Is looking for ``dev/docs/en/documentationparsertest/2.4/subfolder/`` but its up having test/ before subfolder/. I think it maybe simply the case that there needs to be another check for relative links beginning with a "#" and rewrite them to include the page's relative link as well as the hash. I'll see if I can put something more tangible in the tomorrow for this.
