### ISSUE TITLE
"All" page should only list an item once for the stable version

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-docsviewer#127]
Example:

![Duplicated titles](https://cloud.githubusercontent.com/assets/5170590/20943546/c3708d58-bc64-11e6-9f2f-594ed88b1d62.png)

Given that we are viewing `/en/all` and no version is implied by the URL, the docs viewer currently displays every topic title for every version. This results in many duplicated titles/versions.

In this instance should we assume the stable version, and use that to list the topic titles just once?

cc @tractorcow

**Comment by tractorcow** [comment]
Yep that would be nice. It seems a bit excessive to list everything.

How about forcing 'all' to a version? e.g. 'https://docs.silverstripe.org/en/3/all' instead of 'https://docs.silverstripe.org/en/all'

**Comment by robbieaverill** [comment]
I like that. Then you can still list all topics by each version. Will update my pull request.

**Comment by robbieaverill** [comment]
@tractorcow I've updated the PR a little to include the version in the URL while still filtering by it.
