### ISSUE TITLE
Linking to 4.0 (master) API docs

### ISSUE THREAD

**Issue by EtherealTallow** [silverstripe/silverstripe-docsviewer#129]
While reviewing the Silverstripe 4 documentation I came across a link that is supposed to lead to a page on the Silverstripe 4 api docs. 

The link in question tries to link to [i18n::set_locale()](http://api.silverstripe.org/4/class-i18n.html#_set_locale) with `[api:i18n::set_locale()]`, but this link is invalid as the api docs for this class in 4.0 are under [master](http://api.silverstripe.org/master/class-SilverStripe.i18n.i18n.html#_set_locale), as opposed to 4. 

Further digging has revelaled that the documentation is littered with these broken links

**Comment by robbieaverill** [comment]
Thanks Jordan, yes I think we need to push up a 4 branch of the API docs to cover this
