### ISSUE TITLE
All [api] shortcode links are broken

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-docsviewer#132]
Since we've moved to major version branches e.g. 4.x and 3.x, the version passed into the API website search URL is `4` or `3`.

**SS4 docs:** The 4 branch doesn't exist yet, and could temporarily be changed to "master", although this could also be handled [here](https://github.com/silverstripe/api.silverstripe.org/blob/master/htdocs/search/lookup.php) in the API site code which might be prefereable.

**SS3 docs:** Currently the SS3 docs are passing `3` as the branch name, which isn't valid for the API site as it looks at minor versions. Otherwise, the version should be passed in as the stable minor version. The way the docs site is structuring it with major versions only, the stable minor is not available. This could also be handled temporarily with an htaccess redirect in api.silverstripe.org, or we could add another configuration parameter like `ApiLinkBranch: 3.6` for example to docsviewer configuration.

Lastly, for namespaced API shortcode references, we need to convert to dot notation to match the API search format, e.g. `\SilverStripe\ORM\DataExtension` -> `SilverStripe.ORM.DataExtension`. This would be changed [here](https://github.com/silverstripe/silverstripe-docsviewer/blob/master/code/DocumentationParser.php#L287-L312).

---

Another alternative to the minor version branching mentioned above is that the API site could do a similar move as docs.ss (and soon userhelp.ss) and move to major version API docs only: 4.x and 3.x. Thoughts on this?

---

Related issues:

* https://github.com/silverstripe/silverstripe-docsviewer/issues/129
* https://github.com/silverstripe/api.silverstripe.org/issues/32
* https://github.com/silverstripe/silverstripe-framework/issues/5757
* https://github.com/silverstripe/api.silverstripe.org/issues/33

**Comment by SpiritLevel** [comment]
@robbieaverill Yes, major version grouping for all documentation seems the way to go. I'll fix up the DocumentationParser code once decisions made.

**Comment by robbieaverill** [comment]
@SpiritLevel I'm actually not sure I agree when it comes to API docs, since semver would allow us to add infinite API changes as long as they're backwards compatible. For now I've fixed this at the API site's end: https://github.com/silverstripe/api.silverstripe.org/pull/37

**Comment by SpiritLevel** [comment]
Hmm...If the api site always picks the latest minor version, say 3.6, for each major version, here it is 3, then the api docs are "backwards compatible" in the sense that the api docs for 3.6 cover everything for 3.x with x<6. If someone is using, say, 3.4 and wants a feature that they read about in the 3.6 api docs they can easily upgrade from 3.4 to 3.6. Hence, it seems like one could get away with only using the latest minor version for each major version in the docs. It seems to me that it would be simpler to only have docs, across the board, organised by latest minor version....:)
