### ISSUE TITLE
Upgrade to SilverStripe 4 (or don't?)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-docsviewer#133]
Before spending a lot of time on upgrading this module to SS4, we should resolve the discussion around moving doc.silverstripe.org to a third party documentation service: https://github.com/silverstripe/doc.silverstripe.org/issues/157

While I acknowledge that docsviewer is used in other contexts, it significantly lowers our need to upgrade it if we're not using it on doc.ss.org. I see docsviewer (and the related maintenance around doc.ss.org) as a moderate distraction for SS Ltd, which could be better spent elsewhere. Our Markdown isn't *that* special :D

**Comment by robbieaverill** [comment]
cc @SpiritLevel

**Comment by SpiritLevel** [comment]
@robbieaverill: Is the docsviewer module important for people developing on the CWP ?

**Comment by robbieaverill** [comment]
@SpiritLevel no I don't believe so, but the CWP website does use it

**Comment by SpiritLevel** [comment]
Well...does the fact that the CWP website uses docsviewer indicate CWP developers expect the docsviewer module to be available? If so, then, assuming the CWP is important to SS Ltd,  it appears docsviewer must become supported by SS Ltd. and hence upgraded to SS4. I'm happy for my assumptions & reasoning to be shown as faulty :)

**Comment by robbieaverill** [comment]
CWP devs (and other users) would expect there to be docs available on the website, I don't believe that anyone would mind if we replaced the underlying libraries while still delivering the content in the same places in the website information architecture

**Comment by SpiritLevel** [comment]
@robbieaverill Your comment above taken together with that made by @chillu [here](https://github.com/silverstripe/doc.silverstripe.org/issues/157) seems to suggest the idea of replacing docsviewer with something else that uses reStructuredText is being floated...

**Comment by robbieaverill** [comment]
@SpiritLevel yeah the discussion in https://github.com/silverstripe/doc.silverstripe.org/issues/157 around using RTD instead is the most obvious alternative at this stage

**Comment by robbieaverill** [comment]
cc @be2n @nwilliams16

**Comment by be2n** [comment]
Where did we get on this issue? The module has been removed from the 2.0 upgrade programme. 

Has a third party service @chillu suggested been identified?

**Comment by robbieaverill** [comment]
There's some discussion around using readthedocs.org here: https://github.com/silverstripe/doc.silverstripe.org/issues/157

At the time of writing it didn't support themes for markdown repositories though, so we might either need to convert to a different format of documentation (big job) or live with a lack of theming.

**Comment by be2n** [comment]
Do we have a time horizon in regards to when a decision needs to be made?

**Comment by robbieaverill** [comment]
It's not pressing. We won't be able to put docs.silverstripe.org, cwp.govt.nz or userhelp.silverstripe.org onto SilverStripe 4 without upgrading this module first though.

**Comment by UndefinedOffset** [comment]
If there's still interest in doing this, I'm actually attempting to upgrade it as we use it as the foundation/base for our module [webbuilders-group/silverstripe-cmsuserdocs](https://github.com/webbuilders-group/silverstripe-cmsuserdocs).

**Comment by UndefinedOffset** [comment]
One issue I'm running into is the search, it's using Zend_Search_Lucene which doesn't seem to have a supported version in [Zend Framework](https://github.com/zendframework/ZendSearch) anymore, it hasn't been updated in 4 years. I have a feeling even if we pack in the 1.12 version that is currently included and add the missing components it won't work on PHP 7+ anyways.

**Comment by robbieaverill** [comment]
@UndefinedOffset thanks for looking into this. My suggestion would be to remove Lucene support in SilverStripe 4 - we usually promote using Solr for searching, or the OOB full text search engine in core. We don't use Lucene on the SilverStripe docs site FYI.

Related issues: https://github.com/zendframework/ZendSearch/issues/24 https://github.com/salesagility/SuiteCRM/issues/3352

**Comment by UndefinedOffset** [comment]
Sounds good to me I'll strip out the search related stuff from the module then [my progress is here](https://github.com/webbuilders-group/silverstripe-docsviewer/tree/silverstripe-4). It's almost ready to open a pull I think, struggling to get the routing working right now dev/docs seems to be getting handled by DevelopmentAdmin right now.

**Comment by sminnee** [comment]
FYI — docs.silverstripe.org is now running a Gatsby-based solution. The CWP docs are still running with this module and SS3.

**Comment by chillu** [comment]
I think the general consensus from the current module maintainers is that we're not planning a 4.x upgrade, so this issue is noise - I'll close it. If anyone wants to take on the maintenance of a 4.x compatible version and coordinate an upgrade, they can reopen it :)
