### ISSUE TITLE
Sitemap.xml generation to prioritise latest stable docs

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-docsviewer#143]
I find that google searches like [silverstripe file](https://www.google.ca/search?q=silverstripe+file) often return results for outdated versions of SilverStripe, even going back to 3.0.

I wonder if this module could automatically generate a sitemap.xml file that sets the priority of the stable channel to high, and unreleased and old versions to low? Hopefully that would signal to Google that they should surface e.g. _api.silverstripe.org/en/**3.6**/class-File.html_ ahead of _api.silverstripe.org/en/**3.1**/class-File.html_.

**Comment by robbieaverill** [comment]
We recently added a canonical URL which redirects to the latest stable - does that help?

**Comment by jonom** [comment]
Oh cool. I guess that just hasn't shipped to the docs website yet? I can't see a canonical tag on the [SS3.1 File page](http://api.silverstripe.org/en/3.1/class-File.html) for example.

That should probably work well though. I don't know how aggressively Google responses to canonical URLs, if it totally removes older versions of docs from it's index it might be overkill. But still better than the current situation.

**Comment by robbieaverill** [comment]
We did deploy it to docs.silverstripe.org, but the API site doesn't use docsviewer. We will be doing some work on the API site soon though, so will ensure we get some canonicals in for that too :)

**Comment by jonom** [comment]
Ohhhhh :P sorry for dumbness. Thanks Robbie

**Comment by robbieaverill** [comment]
Nothing dumb about this question! Cheers @jonom

**Comment by dhensby** [comment]
> That should probably work well though. I don't know how aggressively Google responses to canonical URLs, if it totally removes older versions of docs from it's index it might be overkill. But still better than the current situation.

Canonical tags are used as silent 301s all the other docs will be removed from google's indexes in favour of the canonical
