### ISSUE TITLE
Mark as unsupported?

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-docsviewer#156]
Now that https://docs.silverstripe.org/ has been rewritten to use Gatsby instead of this module, it's unlikely that anyone from Silverstripe will be supporting it. It begs the question — will anyone else?

The maintainer is listed as @wilr but I don't know if that's historical or still a commitment he's wanting to retain. @chillu @Martimiz @camfindlay @robbieaverill @UndefinedOffset @halkyon @SpiritLevel and @sachajudd are the top-10 committers.

If someone wants to put up their hand for support, then awesome, but otherwise should we add a "deprecated" note to the header, abandoned warning to the composer metadata, and/or move to https://github.com/silverstripe-archive ?

Maybe we leave this ticket open until end of January and if there has been no takers migrate as suggested. I'd probably do all of:

 * [ ] Mark on composer/packagist as abandoned
 * [ ] Move repo to https://github.com/silverstripe-archive
 * [ ] Add a deprecated note to readme
 * [ ] Close open RFCs and enhancements

**Comment by robbieaverill** [comment]
Do we still need to support it for the CWP docs? I assume userhelp will transfer time a Gatsby site at some point too

**Comment by wilr** [comment]
@sminnee we use it internally on a whole lotta things  so happy to transfer it to me to continue to maintain if you don't want it on the org.

**Comment by sminnee** [comment]
> Do we still need to support it for the CWP docs?

...good point. So realistically we're probably looking to keep running it for another year at least.

@wilr perhaps we re-open that discussion then?

Moving it off the github org isn't critical; I just wanted to have some clarity as to whether anyone was gonna still maintain this module, to which the answer is "yep, Will still needs it" ;)

Do you imagine you'd get around to an SS4 upgrade, though? :p

**Comment by sminnee** [comment]
Gonna close this issue, then since it's not relevant for the next wee while 😊

**Comment by wilr** [comment]
@sminnee SS4 upgrade is sitting in a PR waiting for a rebase and merge https://github.com/silverstripe/silverstripe-docsviewer/pull/150/files
