### ISSUE TITLE
Links to namespaced classes are broken

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-docsviewer#37]
If I am not mistaken, then `[api:SilverStripe\Framework\Injector\Factory]` in https://github.com/silverstripe/silverstripe-framework/blob/3.1/docs/en/reference/injector.md will be turned into a link to the API docs.

the link should be: 

```
http://api.silverstripe.org/3.1/class-SilverStripe.Framework.Injector.Factory.html
```

however, currently the generated link is:

```
http://api.silverstripe.org/3.1/class-SilverStripeFrameworkInjectorFactory.html
```

which is 404

**Comment by robbieaverill** [comment]
We've fixed this at the SilverStripe API site end with https://github.com/silverstripe/api.silverstripe.org/issues/33 https://github.com/silverstripe/silverstripe-framework/pull/6895 https://github.com/silverstripe/api.silverstripe.org/pull/37 https://github.com/silverstripe/api.silverstripe.org/pull/38
