### ISSUE TITLE
Closing header tags (#, ## ... ) render out to page

### ISSUE THREAD

**Issue by danaenz** [silverstripe/silverstripe-docsviewer#56]
[Relevant pull request in Beta docs where the hashes are rendering](https://github.com/silverstripe/silverstripe-framework/pull/3744).

[Example page where the tags render in Beta SS docs](http://beta.doc.silverstripe.org/en/developer_guides/customising_the_admin_interface/how_tos/customise_cms_tree/).

And a screenshot: 
![capture](https://cloud.githubusercontent.com/assets/6868265/5520336/75b1e92a-89e1-11e4-9e66-532a4f1a6451.PNG)

**Comment by robbieaverill** [comment]
Hey @danaenz - this looks fixed. Can you confirm? Thanks

**Comment by robbieaverill** [comment]
Hi @danaenz - I'll close this as it appears to be fixed. Please reopen if you think this is still an issue.
