### ISSUE TITLE
default version number cannot be directly accessed

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-docsviewer#60]
for example if my version `3.1` is default I can access this via site/en/ and not site/en/3.1/ - which makes permalinks to certain documentation for versions a pain point. Suggest both should be accessable with the default /en/ setting a canonical meta tag to the version perhaps?

**Comment by NGlasl** [comment]
Just bumping this with an example that going to http://doc.silverstripe.org/en/3.1 should rather result in http://doc.silverstripe.org/en/developer_guides (as this contains the 3.1 documentation that people may be looking for). This has resulted in a number of links (such as 3.1) to not direct where you'd expect.

@wilr

**Comment by dhensby** [comment]
Yes, we need a way to have perma links

**Comment by tractorcow** [comment]
Current changelogs on the site are broken, by the way, until we fix this. Either the site needs to change to exclude the '3.1' in the url or we need to respect it in the docs.

is it safe to remove the 3.1 from the link, and should we make the above change, will the 'default' path continue to work?
