### ISSUE TITLE
Develop branch

### ISSUE THREAD

**Issue by camfindlay** [silverstripe/silverstripe-docsviewer#96]
@SpiritLevel we had a develop branch going for docsviewer however I see your recent PRs have gone direct into master. Can you please check https://github.com/silverstripe/silverstripe-docsviewer/commits/develop and let me know if any commits here that are important are missing from master. I'd like to tidy that up and drop the develop branch as long as we have accounted for these.

Thanks.

**Comment by SpiritLevel** [comment]
@camfindlay Yup....everything I did on develop is now in master :) I guess I was feeling impatient and thought that submitting PRs on master would eliminate a step!

What branch do you want to do the refactor on ? Master ?

**Comment by camfindlay** [comment]
Which refactor?

**Comment by SpiritLevel** [comment]
The one discussed here: https://github.com/silverstripe/silverstripe-docsviewer/pull/94  :)

**Comment by SpiritLevel** [comment]
And see also https://github.com/silverstripe/silverstripe-docsviewer/pull/69

**Comment by camfindlay** [comment]
#94 already merged

**Comment by SpiritLevel** [comment]
Yup.... https://github.com/silverstripe/silverstripe-docsviewer/pull/94 was for the api: tag bugfix but later in the discussion the idea of refactoring docsviewer arose and continues...and this involves deciding on the syntax for any extension to Parsedown. @camfindlay Would this be best discussed first on the dev google group ? Or should we just plough ahead here in PRs/Issues ?

**Comment by camfindlay** [comment]
@SpiritLevel It's only relevant to this module so don't think it requires a dev list chat. Raise a PR as a starting point to propose a change and begin discussion here I think would be the way to go. That way we keep the code and conversation all together.

**Comment by SpiritLevel** [comment]
OK...I'll raise an issue here entitled "Docsviewer Refactor" as a central discussion thread and this can refer to PRs associated with particular aspects of the refactor. Sound good ?
